var configData = {
	"pageContent": "Our Adverse Event Search System (AESS) is designed to retrieve information from U.S. Food and Drug Administration's (FDA) post-marketing safety surveillance program for all approved drug and therapeutic biologic products.  The easy to use search provides adverse events and medication errors that might occur with these marketed products",
  	"countryList": [
    	"GLOBALLY", 
    	"AALAND ISLANDS", 
    	"AFGHANISTAN", 
    	"ALAND ISLANDS", 
    	"ALBANIA", 
    	"ALGERIA", 
    	"AMERICAN SAMOA", 
    	"AN", 
    	"ANDORRA", 
    	"ANGOLA", 
    	"ANGUILLA", 
    	"ANTARCTICA", 
    	"ANTIGUA AND BARBUDA", "ARGENTINA", "ARMENIA", "ARUBA", "AUSTRALIA", "AUSTRIA", "AZERBAIJAN", "BAHAMAS", "BAHRAIN", "BANGLADESH", "BARBADOS", "BELARUS", "BELGIUM", "BELIZE", "BENIN", "BERMUDA", "BHUTAN", "BOLIVIA", "BOSNIA &amp; HERZEGOVINA", "BOSNIA AND HERZEGOWINA", "BOTSWANA", "BOUVET ISLAND", "BRAZIL", "BRITAIN (UK)", "BRITISH INDIAN OCEAN TERRITORY", "BRUNEI", "BRUNEI DARUSSALAM", "BULGARIA", "BURKINA FASO", "BURUNDI", "CAMBODIA", "CAMEROON", "CANADA", "CAPE VERDE", "CARIBBEAN NETHERLANDS", "CAYMAN ISLANDS", "CENTRAL AFRICAN REP.", "CHAD", "CHILE", "CHINA", "CHRISTMAS ISLAND", "COCOS (KEELING) ISLANDS", "COLOMBIA", "COMOROS", "CONGO", "CONGO (DEM. REP.)", "CONGO (REP.)", "CONGO, THE DEMOCRATIC REPUBLIC OF THE", "COOK ISLANDS", "COSTA RICA", "COTE D'IVOIRE", "COUNTRY NOT SPECIFIED", "CROATIA", "CROATIA (local name: Hrvatska)", "CUBA", "CURACAO", "CYPRUS", "CZECH REPUBLIC", "DENMARK", "DJIBOUTI", "DOMINICA", "DOMINICAN REPUBLIC", "EAST TIMOR", "ECUADOR", "EGYPT", "EL SALVADOR", "EQUATORIAL GUINEA", "ERITREA", "ESTONIA", "ETHIOPIA", "European Union", "FALKLAND ISLANDS", "FAROE ISLANDS", "FIJI", "FINLAND", "FRANCE", "FRANCE, METROPOLITAN", "FRENCH GUIANA", "FRENCH POLYNESIA", "FRENCH SOUTHERN &amp; ANTARCTIC LANDS", "FRENCH SOUTHERN TERRITORIES", "GABON", "GAMBIA", "GEORGIA", "GERMANY", "GHANA", "GIBRALTAR", "GREECE", "GREENLAND", "GRENADA", "GUADELOUPE", "GUAM", "GUATEMALA", "GUERNSEY", "GUINEA", "GUINEA-BISSAU", "GUYANA", "HAITI", "HEARD ISLAND &amp; MCDONALD ISLANDS", "HONDURAS", "HONG KONG", "HUNGARY", "ICELAND", "INDIA", "INDONESIA", "IRAN", "IRAN (ISLAMIC REPUBLIC OF)", "IRAQ", "IRELAND", "ISLE OF MAN", "ISRAEL", "ITALY", "JAMAICA", "JAPAN", "JERSEY", "JORDAN", "KAZAKHSTAN", "KENYA", "KIRIBATI", "KOREA (NORTH)", "KOREA (SOUTH)", "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF", "KOREA, REPUBLIC OF", "KUWAIT", "KYRGYZSTAN", "LAO PEOPLE'S DEMOCRATIC REPUBLIC", "LAOS", "LATVIA", "LEBANON", "LESOTHO", "LIBERIA", "LIBYA", "LIBYAN ARAB JAMAHIRIYA", "LIECHTENSTEIN", "LITHUANIA", "LUXEMBOURG", "MACAU", "MACEDONIA", "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF", "MADAGASCAR", "MALAWI", "MALAYSIA", "MALDIVES", "MALI", "MALTA", "MARSHALL ISLANDS", "MARTINIQUE", "MAURITANIA", "MAURITIUS", "MAYOTTE", "MEXICO", "MICRONESIA", "MICRONESIA, FEDERATED STATES OF", "MOLDOVA", "MOLDOVA, REPUBLIC OF", "MONACO", "MONGOLIA", "MONTENEGRO", "MONTSERRAT", "MOROCCO", "MOZAMBIQUE", "MYANMAR", "MYANMAR (BURMA)", "NAMIBIA", "NAURU", "NEPAL", "NETHERLANDS", "NETHERLANDS ANTILLES", "NETHERLANDS ANTILLES (retired code)", "NEW CALEDONIA", "NEW ZEALAND", "NICARAGUA", "NIGER", "NIGERIA", "NIUE", "NORFOLK ISLAND", "NORTHERN MARIANA ISLANDS", "NORWAY", "OMAN", "PAKISTAN", "PALAU", "PALESTINE", "PALESTINIAN TERRITORY, OCCUPIED", "PANAMA", "PAPUA NEW GUINEA", "PARAGUAY", "PERU", "PHILIPPINES", "PITCAIRN", "POLAND", "PORTUGAL", "PUERTO RICO", "QATAR", "REUNION", "ROMANIA", "RUSSIA", "RUSSIAN FEDERATION", "RWANDA", "SAINT KITTS AND NEVIS", "SAMOA", "SAMOA (AMERICAN)", "SAMOA (WESTERN)", "SAN MARINO", "SAO TOME &amp; PRINCIPE", "SAUDI ARABIA", "SENEGAL", "SERBIA", "SERBIA AND MONTENEGRO", "SERBIA AND MONTENEGRO (see individual countries)", "SEYCHELLES", "SIERRA LEONE", "SINGAPORE", "SLOVAKIA", "SLOVAKIA (Slovak Republic)", "SLOVENIA", "SOLOMON ISLANDS", "SOMALIA", "SOUTH AFRICA", "SOUTH GEORGIA &amp; THE SOUTH SANDWICH ISLANDS", "SOUTH SUDAN", "SPAIN", "SRI LANKA", "ST BARTHELEMY", "ST HELENA", "ST KITTS &amp; NEVIS", "ST LUCIA", "ST MAARTEN (DUTCH PART)", "ST MARTIN (FRENCH PART)", "ST PIERRE &amp; MIQUELON", "ST VINCENT", "SUDAN", "SURINAME", "SVALBARD &amp; JAN MAYEN", "SVALBARD AND JAN MAYEN ISLANDS", "SWAZILAND", "SWEDEN", "SWITZERLAND", "SYRIA", "SYRIAN ARAB REPUBLIC", "TAIWAN", "TAIWAN, PROVINCE OF CHINA", "TAJIKISTAN", "TANZANIA", "TANZANIA, UNITED REPUBLIC OF", "THAILAND", "TOGO", "TOKELAU", "TONGA", "TRINIDAD &amp; TOBAGO", "TRINIDAD AND TOBAGO", "TUNISIA", "TURKEY", "TURKMENISTAN", "TURKS &amp; CAICOS IS", "TUVALU", "UGANDA", "UKRAINE", "UNITED ARAB EMIRATES", "UNITED KINGDOM", "UNITED STATES", "UNITED STATES MINOR OUTLYING ISLANDS", "URUGUAY", "UZBEKISTAN", "VANUATU", "VATICAN CITY", "VATICAN CITY STATE (HOLY SEE)", "VENEZUELA", "VIET NAM", "VIETNAM", "VIRGIN ISLANDS (UK)", "VIRGIN ISLANDS (US)", "WALLIS &amp; FUTUNA", "WALLIS AND FUTUNA ISLANDS", "WESTERN SAHARA", "YEMEN", "YUGOSLAVIA", "ZAIRE", "ZAMBIA", "ZIMBABWE"
  	],
   	"individualSubmitting": [
   		"Physician", 
   		"Pharmacist", 
   		"Other health professional", 
   		"Lawyer", 
   		"Consumer or non-health professional"
   	],
   	"country1": [
   		"one", "two", "threee"
   	]
}